# Generated by Django 3.1.13 on 2022-03-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='is_our_country_of_operation',
        ),
        migrations.AddField(
            model_name='companydetails',
            name='keywords',
            field=models.CharField(default='hopital', max_length=500),
            preserve_default=False,
        ),
    ]
