# Generated by Django 3.1.13 on 2022-03-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20220329_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='sub_title',
            field=models.CharField(max_length=100),
        ),
    ]
