# Generated by Django 3.1.13 on 2022-03-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20220330_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='number_of_beds',
            field=models.IntegerField(default=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydetails',
            name='number_of_doctors',
            field=models.IntegerField(default=51),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydetails',
            name='number_of_internal_patients',
            field=models.IntegerField(default=27500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydetails',
            name='number_of_paramedics',
            field=models.IntegerField(default=191),
            preserve_default=False,
        ),
    ]
