# Generated by Django 3.1.13 on 2022-03-31 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20220330_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetails',
            name='director',
        ),
        migrations.RemoveField(
            model_name='news',
            name='is_breaking_news',
        ),
        migrations.AlterField(
            model_name='event',
            name='formateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.useraccount'),
        ),
        migrations.AlterField(
            model_name='eventcomment',
            name='commented_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.useraccount'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.useraccount'),
        ),
        migrations.AlterField(
            model_name='news',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.useraccount'),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='commented_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.useraccount'),
        ),
        migrations.AlterField(
            model_name='ourpartners',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_added_by', to='main_app.useraccount'),
        ),
        migrations.AlterField(
            model_name='ourpartners',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_representative', to='main_app.useraccount'),
        ),
        migrations.AlterField(
            model_name='ourproject',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.useraccount'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.useraccount'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='testifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.useraccount'),
        ),
    ]
