# Generated by Django 3.1.13 on 2022-03-31 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20220331_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='director',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.useraccount'),
            preserve_default=False,
        ),
    ]
