# Generated by Django 3.1.13 on 2022-03-31 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20220331_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=5000, null=True, unique=True)),
                ('posted_on_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
