# Generated by Django 3.1.13 on 2022-03-31 23:50

from django.db import migrations, models
import main_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='presentation_image',
            field=models.FileField(default=1, upload_to='', validators=[main_app.validators.validate_file_extension]),
            preserve_default=False,
        ),
    ]
