# Generated by Django 3.1.13 on 2022-04-01 13:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import main_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20220401_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fontawesome_icon', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='', validators=[main_app.validators.validate_file_extension])),
                ('description', ckeditor.fields.RichTextField()),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=5000, null=True, unique=True)),
                ('added_on_date_time', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direction_added_by', to='main_app.useraccount')),
                ('deputy_director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deputy_director', to='main_app.useraccount')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='director', to='main_app.useraccount')),
            ],
        ),
    ]
