# Generated by Django 3.1.13 on 2022-04-01 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourproject',
            name='price',
        ),
    ]
