# Generated by Django 3.1.13 on 2022-04-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_dayoftheweek_timetable_workinghour'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='is_break_time',
            field=models.BooleanField(default=False),
        ),
    ]
