# Generated by Django 3.1.13 on 2022-04-02 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_timetable_is_break_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='responsable',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main_app.useraccount'),
            preserve_default=False,
        ),
    ]
