# Generated by Django 3.1.13 on 2022-04-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_timetable_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
