# Generated by Django 3.1.13 on 2022-04-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_useraccount_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
