# Generated by Django 3.1.13 on 2022-04-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_useraccount_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
