# Generated by Django 3.1.13 on 2022-04-04 12:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_useraccount_is_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='admission_preparation',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
