# Generated by Django 3.1.13 on 2022-04-04 12:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_companydetails_admission_preparation'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='daily_life',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
