# Generated by Django 3.1.13 on 2022-04-04 12:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_companydetails_daily_life'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='rights_and_duties',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
