# Generated by Django 3.1.13 on 2022-04-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_companydetails_rights_and_duties'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='ranking',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
