# Generated by Django 3.1.13 on 2022-04-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_auto_20220405_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='email',
        ),
    ]
