# Generated by Django 3.1.13 on 2022-04-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_remove_useraccount_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
