# Generated by Django 3.1.13 on 2022-04-05 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_auto_20220405_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydetails',
            old_name='tel_welcome',
            new_name='tel_reception',
        ),
    ]
