# Generated by Django 3.1.13 on 2022-04-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_auto_20220405_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_rendez_vous',
            field=models.BooleanField(default=False),
        ),
    ]
