# Generated by Django 3.1.13 on 2022-04-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_covid19'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid19',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
