# Generated by Django 3.1.13 on 2022-04-06 12:40

from django.db import migrations, models
import main_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0035_covid19governmentinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid19governmentinformation',
            name='file',
            field=models.FileField(default=1, upload_to='', validators=[main_app.validators.validate_file_extension]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[main_app.validators.validate_file_extension]),
        ),
    ]
