# Generated by Django 3.1.13 on 2022-04-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0036_auto_20220406_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covid19governmentinformation',
            old_name='file',
            new_name='image',
        ),
        migrations.AddField(
            model_name='covid19governmentinformation',
            name='short_description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
