# Generated by Django 3.1.13 on 2022-04-06 13:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0037_auto_20220406_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='privacy_policy',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
