# Generated by Django 3.1.13 on 2022-04-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0038_companydetails_privacy_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourpartners',
            name='is_pharmacy',
            field=models.BooleanField(default=False),
        ),
    ]
